### ISSUE TITLE
Add info for registration fees in the hero page

### ISSUE THREAD

**Issue by zeborg** [hackkrmu/hackkrmu.github.io#12]
The fees for solo/duet/team can be mentioned in the area highlighted below:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37282098/201351166-87a612d1-4cc9-449d-a8c1-335b465a8278.png">

**PLEASE NOTE:**
Checkout to `release-2.0` branch and make changes to it instead of the `2.0` branch, and once the changes are done make a pull request agains the `master` branch.

**Comment by rishavcodes** [comment]
Registration fee element added to home page
